server:
  port: 8081
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: zipkin-sleuth
          uri: https://github.com/JuancaSterba/tutorial-microservicios
          search-paths: config-data