server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/JuancaSterba/tutorial-microservicios
          search-paths: config-data